apiVersion: v1
kind: Service
metadata:
  namespace: nano35
  name: nano35-files-api-svc
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 80
    nodePort: 30005
  selector:
    app: nano35-files-api
